replicaCount: 2

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: "1.25-alpine"

service:
  type: ClusterIP
  port: 80

# These labels will be injected via Helm command flags
# --set commonLabels.team=platform
# --set commonLabels.env=dev
commonLabels: {}

podLabels: {}
